### PR TITLE
Optional countersheet for playing without 3D printer

### PR DESCRIPTION
**Pull request by lifelike**
Countersheet is made using Inkscape and the Countersheetsextension
(see https://github.com/lifelike/countersheetsextension/).

Generated PDF included.

### CODE REVIEW

**Comment by penyuan** [comment]
(let me know if this comment is better in Discussion or Issues!)

In response to @lifelike, I also don't have immediate access to a 3D printer. I wonder if we could do something to have *2D* printable stuff on paper that could be glued onto cut pieces of cardboard and let the game be played that way??? Obvious not as durable as 3D printed plastic, but could work in a pinch?

**Comment by penyuan** [comment]
> The main issue here is it needs to be efficient, because every time a piece is added or changed, this will need doing again!

Oh yeah, great point!!! I am not familiar enough with STLs or OpenSCAD files to know, but it'll be awesome if we can set up some sort of continuous integration process where whenever the CAD files are updated, we automate a "squashing" process that spits out 2D files like SVGs which can then be printed on paper! Hope there's an expert that can chime in on this. 😆

**Comment by penyuan** [comment]
BTW, I found [this thread/post](https://graphicdesign.stackexchange.com/a/118521/251) about projecting a 3D CAD file onto a 2D plane then export as SVG. I don't have time to ponder it at the moment, so will leave the link here for now.

**Comment by lifelike** [comment]
The script that I used in Inkscape to create the countersheet can run from the command-line as well. It still requires Inkscape to be installed, but at least it can be fully automated. If someone can figure out how to create a SVG (or PNG) from the CAD files it should be possible to set up export of the complete sheets.

https://github.com/lifelike/countersheetsextension/wiki/Running-from-Command-Line

**Comment by penyuan** [comment]
I've taken the liberty of creating issue #58 to continue this discussion.

**Pull request merged**
