### PR TITLE
A fancy top proposal that matches the tobacco tin

### PR DESCRIPTION
**Pull request by amnos0405**
This consists of two parts, the first a topper to glue on that features parts of the tobacco tin design. The topper is 'divided' into 5 levels to be able to be able to perform filament swaps of different colors. The bottom level of the topper is 6mm giving 3, 2mm layer height passes. All other levels are 4mm allowing 2, 2mm layer height passes. The second part is a new top that still fits the box bottom, but has corner bevels that match the topper.

### CODE REVIEW

**Comment by amnos0405** [comment]
Images of printed topper with new sized top

**Comment by Winehorn** [comment]
That's awesome!

**Comment by Wollivan** [comment]
This is unbelievably cool, instant merge for me haha! As soon as I have enough different colour filaments I'm going to do this!

Again SUPER weird seeing my name on a box haha

**Comment by Wollivan** [comment]
Please do make a post on r/SquadronLeader because this is sick!

**Comment by amnos0405** [comment]
> This is unbelievably cool, instant merge for me haha! As soon as I have enough different colour filaments I'm going to do this!
> 
> Again SUPER weird seeing my name on a box haha

Oh this is the perfect excuse for a new batch of filament...in all the colors!

**Comment by Wollivan** [comment]
> Oh this is the perfect excuse for a new batch of filament...in all the colours!

That raises a good point, what filament did you use for this fine example!

**Comment by amnos0405** [comment]
> That raises a good point, what filament did you use for this fine example!

eSun: Olive Green, Grey, Black, White
ttyt3D: Silk Red

**Comment by penyuan** [comment]
This is great, especially for us who don't smoke tobacco. 😄

**Comment by Wollivan** [comment]
> This is great, especially for us who don't smoke tobacco. 😄

And for those who shouldn't!

**Pull request merged**
