### PR TITLE
Add printable box

### PR DESCRIPTION
**Pull request by Winehorn**
As I don't have a small box lying around and the replica boxes are out of stock, I created a printable box with roughly the same dimensions!
squadron_leader_box

I'm new to OpenSCAD, so please forgive my code :)

A printable box also allows for some new features: I'm planning to add some indentations to the bottom of the box that can (together with small cubes) be used for health tracking.

### CODE REVIEW

**Comment by Wollivan** [comment]
Unbelievable work! Thank for an epic update!

**Comment by Wollivan** [comment]
Are you a different person to the one commenting on the issue for the box?

**Comment by Winehorn** [comment]
Thanks for merging!

Oh, haven't seen this issue. So yes, I'm a different person!

**Comment by Wollivan** [comment]
Haha amazing!

Can I put your name in the thanks, and if yes... What is it?

**Comment by Winehorn** [comment]
Sure! It's Flo :)

**Pull request merged**
