### PR TITLE
Rules/range ruler change

### PR DESCRIPTION
**Pull request by Wollivan**
Please let me know what you think.

I will be merging this weekend, but am open to changes if people think this doesn't work.

### CODE REVIEW

**Comment by Wollivan** [comment]
After rereading all the changes in this PR, and thinking about the solo campaign rules, I'm almost certain this is something that needs to be included.

I will still wait till tomorrow to merge in case anyone has some changes, but the inclusion of 3 ranges will allow for so much better design on the campaigns.

**Comment by Winehorn** [comment]
I think the multi-range ruler is a good idea that opens up a lot of possibilites!

Do you think it's possible to split the ruler into 3 separate interlocking pieces? That way it would fit in the box without risk of breaking it. Or maybe use some kind of print-in-place hinge?

**Comment by Wollivan** [comment]
> Do you think it's possible to split the ruler into 3 separate interlocking pieces?


Why didn't I think of that! I'll get to work on that!

**Comment by Wollivan** [comment]
I am going to merge this, then get to work on creating a ruler that can be taken apart.

**Pull request merged**
